---
- hosts: raspis
  become: yes

  roles:
    - apps
    - maintenance
    - sudoers

  post_tasks:
    - name: Reboot al terminar todo
      ansible.builtin.reboot:
        msg: "Reinicio automático después del deploy"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami