---
- hosts: raspis
  become: yes

  roles:
    - apps
    - maintenance
    - sudoers

  post_tasks:
    - name: Reboot (SSH remoto)
      ansible.builtin.reboot:
        msg: "Reinicio automático después del deploy"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: ansible_connection != 'local'

    - name: "Reboot (host local - desacoplado)"
      ansible.builtin.shell: "sleep 2 && /sbin/shutdown -r now 'reboot post-deploy'"
      async: 1
      poll: 0
      ignore_errors: true
      when: ansible_connection == 'local'