---
# ---------- Paquetes base ----------
- name: Instalar paquetes base
  apt:
    name: "{{ apt_base_packages }}"
    update_cache: yes
  become: yes

- name: Instalar unclutter (oculta cursor inactivo)
  apt:
    name: unclutter
    state: present
    update_cache: yes
  become: yes

# ---------- Directorios ----------
- name: Crear directorios base
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: "0755"
  loop:
    - "{{ electron_root }}"
    - "{{ signage_root }}"
  become: yes

# --- SSH keys en el target ---
- name: Crear ~/.ssh
  file:
    path: "/home/{{ kiosk_user }}/.ssh"
    state: directory
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: "0700"
  become: yes

- name: Copiar llave electron
  copy:
    src: "{{ playbook_dir }}/secrets/id_ed25519_electron"
    dest: "/home/{{ kiosk_user }}/.ssh/id_ed25519_electron"
    mode: "0600"
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
  become: yes
  no_log: true

- name: Copiar llave signage
  copy:
    src: "{{ playbook_dir }}/secrets/id_ed25519_signage"
    dest: "/home/{{ kiosk_user }}/.ssh/id_ed25519_signage"
    mode: "0600"
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
  become: yes
  no_log: true

- name: Asegurar known_hosts (GitHub)
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa,ecdsa,ed25519 github.com') }}"
    path: "/home/{{ kiosk_user }}/.ssh/known_hosts"
    state: present
  become: yes
  become_user: "{{ kiosk_user }}"

- name: Configurar ~/.ssh/config (default + alias github-signage)
  blockinfile:
    path: "/home/{{ kiosk_user }}/.ssh/config"
    create: yes
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: "0600"
    block: |
      Host github.com
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_ed25519_electron
        IdentitiesOnly yes
        StrictHostKeyChecking accept-new

      # Usa este alias solo si el remoto de signage es git@github-signage:...
      Host github-signage
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_ed25519_signage
        IdentitiesOnly yes
        StrictHostKeyChecking accept-new
  become: yes

# Solo si tu remoto de signage usa git@github-signage:...
- name: Config ~/.ssh/config con alias github-signage
  blockinfile:
    path: "/home/{{ kiosk_user }}/.ssh/config"
    create: yes
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: "0600"
    block: |
      Host github.com
        User git
        IdentityFile ~/.ssh/id_ed25519_electron
        IdentitiesOnly yes

      Host github-signage
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_ed25519_signage
        IdentitiesOnly yes
  when: electron_repo is search('github-signage') or signage_repo is search('github-signage')
  become: yes

# ---------- Clonar/actualizar repos ----------
- name: Clonar/actualizar electron_rasp
  git:
    repo: "{{ electron_repo }}"
    dest: "{{ electron_root }}/electron_rasp"
    version: "{{ electron_branch }}"
    force: yes
    accept_hostkey: yes
    key_file: "/home/{{ kiosk_user }}/.ssh/id_ed25519_electron"
  become: yes
  become_user: "{{ kiosk_user }}"

- name: Clonar/actualizar signage
  git:
    repo: "{{ signage_repo }}"
    dest: "{{ signage_root }}/signage"
    version: "{{ signage_branch }}"
    force: yes
    accept_hostkey: yes
    key_file: "/home/{{ kiosk_user }}/.ssh/id_ed25519_signage"
  become: yes
  become_user: "{{ kiosk_user }}"

# ---------- Python venv + requirements ----------
- name: Crear venv (si no existe)
  command: "{{ python_bin }} -m venv {{ venv_dir }}"
  args: { creates: "{{ venv_dir }}/bin/activate" }
  become: yes
  become_user: "{{ kiosk_user }}"

- name: Instalar requirements (Flask)
  command: "{{ venv_dir }}/bin/pip install --upgrade -r {{ requirements_file }}"
  become: yes
  become_user: "{{ kiosk_user }}"

# ---------- NPM para Electron ----------
- name: Instalar dependencias npm (electron)
  command: npm ci
  args:
    chdir: "{{ electron_app_dir }}"
  become: yes
  become_user: "{{ kiosk_user }}"

# ---------- Scripts de auto-pull (copiados 1:1 de tu Pi) ----------
- name: Instalar update_repo.sh (electron)
  copy:
    src: update_repo.sh
    dest: "{{ electron_root }}/update_repo.sh"
    mode: "0755"
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
  become: yes

- name: Instalar signage update.sh
  copy:
    src: signage_update.sh
    dest: "{{ signage_root }}/signage/update.sh"
    mode: "0755"
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
  become: yes

# ---------- systemd: services/timers ----------
- name: electron_rasp-electron.service
  template:
    src: electron_rasp-electron.service.j2
    dest: /etc/systemd/system/electron_rasp-electron.service
    mode: "0644"
  notify: [reload systemd]
  become: yes

- name: Crear dir para drop-ins de electron
  file:
    path: /etc/systemd/system/electron_rasp-electron.service.d
    state: directory
    mode: "0755"
  become: yes

- name: Drop-in override (CPU + flags)
  template:
    src: electron_rasp-electron.override.conf.j2
    dest: /etc/systemd/system/electron_rasp-electron.service.d/override.conf
    mode: "0644"
  notify: [reload systemd]
  become: yes

- name: electron_rasp-flask.service
  template:
    src: electron_rasp-flask.service.j2
    dest: /etc/systemd/system/electron_rasp-flask.service
    mode: "0644"
  notify: [reload systemd]
  become: yes

- name: electron_rasp-update.service
  template:
    src: electron_rasp-update.service.j2
    dest: /etc/systemd/system/electron_rasp-update.service
    mode: "0644"
  notify: [reload systemd]
  become: yes

- name: electron_rasp-update.timer
  template:
    src: electron_rasp-update.timer.j2
    dest: /etc/systemd/system/electron_rasp-update.timer
    mode: "0644"
  notify: [reload systemd]
  become: yes

- name: signage-update.service
  template:
    src: signage-update.service.j2
    dest: /etc/systemd/system/signage-update.service
    mode: "0644"
  notify: [reload systemd]
  become: yes

- name: signage-update.timer
  template:
    src: signage-update.timer.j2
    dest: /etc/systemd/system/signage-update.timer
    mode: "0644"
  notify: [reload systemd]
  become: yes

- name: Habilitar y arrancar servicios/timers
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - electron_rasp-flask.service
    - electron_rasp-electron.service
    - electron_rasp-update.timer
    - signage-update.timer
  become: yes

# ---------- LightDM autologin (opcional) ----------
- name: Configurar autologin en LightDM (opcional)
  ini_file:
    path: /etc/lightdm/lightdm.conf
    section: "Seat:*"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    backup: yes
  loop:
    - { option: "autologin-user",   value: "{{ lightdm_autologin_user }}" }
    - { option: "autologin-session", value: "{{ lightdm_session }}" }
    - { option: "user-session",      value: "{{ lightdm_session }}" }
    - { option: "xserver-command",   value: "X" }
  when: manage_lightdm
  become: yes

- name: Habilitar lightdm (display manager)
  systemd:
    name: lightdm.service
    enabled: yes
    state: started
  when: manage_lightdm
  become: yes

- name: Crear carpeta de autostart del usuario
  file:
    path: "/home/{{ kiosk_user }}/.config/lxsession/{{ lightdm_session }}"
    state: directory
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: "0755"
  become: yes

- name: Configurar autostart (unclutter + xset) en LXDE
  copy:
    dest: "/home/{{ kiosk_user }}/.config/lxsession/{{ lightdm_session }}/autostart"
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: "0644"
    content: |
      @xset s off
      @xset -dpms
      @xset s noblank
      @unclutter -idle 1 -root -noevents
  become: yes

- name: Instalar unit signage-update.service
  template:
    src: signage-update.service.j2
    dest: /etc/systemd/system/signage-update.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Asegurar timer habilitado
  systemd:
    name: signage-update.timer
    enabled: yes
    state: started

# --- Remotos (AnyDesk/TeamViewer): asegurar des-mask, enable y start ---

- name: Recoger facts de servicios
  service_facts:

# (Opcional pero útil) Quitar hard-mask si existe (/etc/systemd/system/<svc> -> /dev/null)
- name: Quitar hard-mask de teamviewerd si apunta a /dev/null
  stat:
    path: /etc/systemd/system/teamviewerd.service
  register: tvd_unit
  become: yes

- name: Eliminar symlink / hard-mask de teamviewerd
  file:
    path: /etc/systemd/system/teamviewerd.service
    state: absent
  when: tvd_unit.stat.islnk is defined and tvd_unit.stat.islnk and tvd_unit.stat.lnk_target == '/dev/null'
  become: yes

- name: daemon-reload por si quitamos hard-mask
  systemd:
    daemon_reload: yes
  become: yes

# Unmask + enable + start para cada remoto que exista en el host
- name: Asegurar remotos unmasked/enabled/running
  systemd:
    name: "{{ item }}"
    masked: no               # ← clave para evitar el 'is masked'
    enabled: yes
    state: started
  loop: "{{ remote_services }}"
  when: item in ansible_facts.services | default({})  # sólo si el servicio existe
  register: remote_result
  failed_when: false         # no ocultes todo; sólo evita que el play muera
  become: yes

# (Opcional) Mostrar qué pasó con cada remoto
- name: Debug de remotos
  debug:
    var: remote_result.results | map(attribute='name') | list